import { CityType, importedCitiesType } from "./dataType";

export const citiesMockData: importedCitiesType = [
  {
    id: "101",
    Pre: "富山県",
    Mun: "富山市",
    Pop: "413969",
    Url: "https://www.city.toyama.toyama.jp/index.html",
    Temp_Jan: "2.3",
    Temp_July: "26.4",
    Snow_Jan: "202cm",
    Bicthe_num: "261",
    Bicthe_rate: "0.063%",
    Carthe_num: "7",
    Carthe_rate: "0.002%",
    Carac_num: "1435",
    Carac_rate: "0.347%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "102",
    Pre: "富山県",
    Mun: "高岡市",
    Pop: "166300",
    Url: "https://www.city.takaoka.toyama.jp/",
    Temp_Jan: "6.7",
    Temp_July: "21.5",
    Snow_Jan: "266cm",
    Bicthe_num: "86",
    Bicthe_rate: "0.052%",
    Carthe_num: "7",
    Carthe_rate: "0.004%",
    Carac_num: "296",
    Carac_rate: "0.178%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "103",
    Pre: "富山県",
    Mun: "魚津市",
    Pop: "41032",
    Url: "https://www.city.uozu.toyama.jp/",
    Temp_Jan: "2.1",
    Temp_July: "25.8",
    Snow_Jan: "170cm",
    Bicthe_num: "6",
    Bicthe_rate: "0.01%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "51",
    Carac_rate: "0.12%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "104",
    Pre: "富山県",
    Mun: "氷見市",
    Pop: "44081",
    Url: "https://www.city.himi.toyama.jp/",
    Temp_Jan: "1.6",
    Temp_July: "25.6",
    Snow_Jan: "216cm",
    Bicthe_num: "6",
    Bicthe_rate: "0.01%",
    Carthe_num: "1",
    Carthe_rate: "0.002%",
    Carac_num: "48",
    Carac_rate: "0.11%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "105",
    Pre: "富山県",
    Mun: "滑川市",
    Pop: "32415",
    Url: "http://www.city.namerikawa.toyama.jp/",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "14",
    Bicthe_rate: "0.043%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "65",
    Carac_rate: "0.20%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "106",
    Pre: "富山県",
    Mun: "黒部市",
    Pop: "39842",
    Url: "https://www.city.kurobe.toyama.jp/index.aspx",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "6",
    Bicthe_rate: "0.02%",
    Carthe_num: "2",
    Carthe_rate: "0.005%",
    Carac_num: "37",
    Carac_rate: "0.09%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "107",
    Pre: "富山県",
    Mun: "砺波市",
    Pop: "47796",
    Url: "https://www.city.tonami.toyama.jp/",
    Temp_Jan: "1.6",
    Temp_July: "25.8",
    Snow_Jan: "207cm",
    Bicthe_num: "6",
    Bicthe_rate: "0.01%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "103",
    Carac_rate: "0.21%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "108",
    Pre: "富山県",
    Mun: "小矢部市",
    Pop: "28792",
    Url: "http://www.city.oyabe.toyama.jp/",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "3",
    Bicthe_rate: "0.01%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "42",
    Carac_rate: "0.15%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "109",
    Pre: "富山県",
    Mun: "南砺市",
    Pop: "47698",
    Url: "https://www.city.nanto.toyama.jp/cms-sypher/www/index.jsp",
    Temp_Jan: "1.8",
    Temp_July: "25.7",
    Snow_Jan: "NULL",
    Bicthe_num: "1",
    Bicthe_rate: "0.002%",
    Carthe_num: "1",
    Carthe_rate: "0.002%",
    Carac_num: "63",
    Carac_rate: "0.13",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "110",
    Pre: "富山県",
    Mun: "射水市",
    Pop: "90334",
    Url: "https://www.city.imizu.toyama.jp/top.aspx",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "29",
    Bicthe_rate: "0.032%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "263",
    Carac_rate: "0.29%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "111",
    Pre: "富山県",
    Mun: "舟橋村",
    Pop: "3179",
    Url: "http://www.vill.funahashi.toyama.jp/",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "2",
    Bicthe_rate: "0.06%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "NULL",
    Carac_rate: "NULL",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "112",
    Pre: "富山県",
    Mun: "上市町",
    Pop: "19462",
    Url: "https://www.town.kamiichi.toyama.jp/",
    Temp_Jan: "0.1",
    Temp_July: "24.2",
    Snow_Jan: "NULL",
    Bicthe_num: "4",
    Bicthe_rate: "0.02%",
    Carthe_num: "1",
    Carthe_rate: "0.005%",
    Carac_num: "76",
    Carac_rate: "0.39%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "113",
    Pre: "富山県",
    Mun: "立山町",
    Pop: "25091",
    Url: "https://www.town.tateyama.toyama.jp/",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "3",
    Bicthe_rate: "0.01%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "NULL",
    Carac_rate: "NULL",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "114",
    Pre: "富山県",
    Mun: "入善町",
    Pop: "23724",
    Url: "https://www.town.nyuzen.toyama.jp/",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "5",
    Bicthe_rate: "0.02%",
    Carthe_num: "1",
    Carthe_rate: "0.004%",
    Carac_num: "25",
    Carac_rate: "0.11%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "115",
    Pre: "富山県",
    Mun: "朝日町",
    Pop: "10955",
    Url: "https://www.town.asahi.toyama.jp/",
    Temp_Jan: "1.8",
    Temp_July: "25.7",
    Snow_Jan: "205cm",
    Bicthe_num: "0",
    Bicthe_rate: "0%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "NULL",
    Carac_rate: "NULL",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "201",
    Pre: "石川県",
    Mun: "金沢市",
    Pop: "451018",
    Url: "https://www4.city.kanazawa.lg.jp/index.html",
    Temp_Jan: "3.9",
    Temp_July: "27.0",
    Snow_Jan: "101cm",
    Bicthe_num: "349",
    Bicthe_rate: "0.077%",
    Carthe_num: "2",
    Carthe_rate: "0.0004%",
    Carac_num: "1032",
    Carac_rate: "0.229%",
    Snathe_num: "3",
    Snathe_rate: "0.0007%",
  },
  {
    id: "202",
    Pre: "石川県",
    Mun: "七尾市",
    Pop: "51178",
    Url: "https://www.city.nanao.lg.jp/",
    Temp_Jan: "2.1",
    Temp_July: "25.8",
    Snow_Jan: "150cm",
    Bicthe_num: "6",
    Bicthe_rate: "0.01%",
    Carthe_num: "1",
    Carthe_rate: "0.002%",
    Carac_num: "59",
    Carac_rate: "0.12%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "203",
    Pre: "石川県",
    Mun: "小松市",
    Pop: "107722",
    Url: "https://www.city.komatsu.lg.jp/",
    Temp_Jan: "3.5",
    Temp_July: "26.4",
    Snow_Jan: "NULL",
    Bicthe_num: "59",
    Bicthe_rate: "0.548%",
    Carthe_num: "2",
    Carthe_rate: "0.002%",
    Carac_num: "213",
    Carac_rate: "0.198%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "204",
    Pre: "石川県",
    Mun: "輪島市",
    Pop: "25638",
    Url: "https://www.city.wajima.ishikawa.jp/",
    Temp_Jan: "2.9",
    Temp_July: "25.5",
    Snow_Jan: "113cm",
    Bicthe_num: "0",
    Bicthe_rate: "0%",
    Carthe_num: "1",
    Carthe_rate: "0.004%",
    Carac_num: "34",
    Carac_rate: "0.13%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "205",
    Pre: "石川県",
    Mun: "珠洲市",
    Pop: "13700",
    Url: "https://www.city.suzu.lg.jp/",
    Temp_Jan: "2.3",
    Temp_July: "25.4",
    Snow_Jan: "222cm",
    Bicthe_num: "3",
    Bicthe_rate: "0.02%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "8",
    Carac_rate: "0.06%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "206",
    Pre: "石川県",
    Mun: "加賀市",
    Pop: "65307",
    Url: "https://www.city.kaga.ishikawa.jp/",
    Temp_Jan: "1.5",
    Temp_July: "24.6",
    Snow_Jan: "244cm",
    Bicthe_num: "17",
    Bicthe_rate: "0.03%",
    Carthe_num: "1",
    Carthe_rate: "0.002%",
    Carac_num: "118",
    Carac_rate: "0.18%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "207",
    Pre: "石川県",
    Mun: "羽咋市",
    Pop: "20940",
    Url: "https://www.city.hakui.lg.jp/",
    Temp_Jan: "3.6",
    Temp_July: "26.4",
    Snow_Jan: "NULL",
    Bicthe_num: "5",
    Bicthe_rate: "0.02%",
    Carthe_num: "1",
    Carthe_rate: "0.005%",
    Carac_num: "34",
    Carac_rate: "0.16%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "208",
    Pre: "石川県",
    Mun: "かほく市",
    Pop: "35668",
    Url: "https://www.city.kahoku.lg.jp/",
    Temp_Jan: "3.2",
    Temp_July: "26.0",
    Snow_Jan: "NULL",
    Bicthe_num: "10",
    Bicthe_rate: "0.03%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "34",
    Carac_rate: "0.10%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "209",
    Pre: "石川県",
    Mun: "白山市",
    Pop: "113496",
    Url: "https://www.city.hakusan.lg.jp/index.html",
    Temp_Jan: "1.2",
    Temp_July: "25.1",
    Snow_Jan: "281cm",
    Bicthe_num: "54",
    Bicthe_rate: "0.048%",
    Carthe_num: "1",
    Carthe_rate: "0.0009%",
    Carac_num: "178",
    Carac_rate: "0.157%",
    Snathe_num: "1",
    Snathe_rate: "0.0009%",
  },
  {
    id: "210",
    Pre: "石川県",
    Mun: "能美市",
    Pop: "49905",
    Url: "https://www.city.nomi.ishikawa.jp/www/index.html",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "7",
    Bicthe_rate: "0.01%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "49",
    Carac_rate: "0.10%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "211",
    Pre: "石川県",
    Mun: "野々市市",
    Pop: "53563",
    Url: "https://www.city.nonoichi.lg.jp/",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "124",
    Bicthe_rate: "0.23%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "5",
    Carac_rate: "0.24%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "212",
    Pre: "石川県",
    Mun: "川北町",
    Pop: "6167",
    Url: "http://www.town.kawakita.ishikawa.jp/",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "0",
    Bicthe_rate: "0%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "5",
    Carac_rate: "0.08%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "213",
    Pre: "石川県",
    Mun: "津幡町",
    Pop: "37551",
    Url: "https://www.town.tsubata.lg.jp/",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "20",
    Bicthe_rate: "0.053%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "29",
    Carac_rate: "0.08%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "214",
    Pre: "石川県",
    Mun: "内灘町",
    Pop: "26441",
    Url: "https://www.town.uchinada.lg.jp/",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "5",
    Bicthe_rate: "0.02%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "26",
    Carac_rate: "0.10%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "215",
    Pre: "石川県",
    Mun: "志賀町",
    Pop: "19552",
    Url: "https://www.town.shika.lg.jp/index.html",
    Temp_Jan: "3.7",
    Temp_July: "26.3",
    Snow_Jan: "NULL",
    Bicthe_num: "0",
    Bicthe_rate: "0%",
    Carthe_num: "4",
    Carthe_rate: "0.02%",
    Carac_num: "16",
    Carac_rate: "0.08%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "216",
    Pre: "石川県",
    Mun: "宝達志水町",
    Pop: "12790",
    Url: "https://www.hodatsushimizu.jp/gyosei/index.html",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "1",
    Bicthe_rate: "0.008%",
    Carthe_num: "1",
    Carthe_rate: "0.008%",
    Carac_num: "11",
    Carac_rate: "0.09%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "217",
    Pre: "石川県",
    Mun: "中能登町",
    Pop: "17619",
    Url: "https://www.town.nakanoto.ishikawa.jp/",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "1",
    Bicthe_rate: "0.006%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "22",
    Carac_rate: "0.13%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "218",
    Pre: "石川県",
    Mun: "穴水町",
    Pop: "7885",
    Url: "https://www.town.anamizu.lg.jp/",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "0",
    Bicthe_rate: "0%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "8",
    Carac_rate: "0.1%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "219",
    Pre: "石川県",
    Mun: "能登町",
    Pop: "16516",
    Url: "http://www.town.noto.lg.jp/www/total_top.jsp",
    Temp_Jan: "1.0",
    Temp_July: "24.3",
    Snow_Jan: "NULL",
    Bicthe_num: "0",
    Bicthe_rate: "0%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "17",
    Carac_rate: "0.10%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "301",
    Pre: "福井県",
    Mun: "福井市",
    Pop: "262126",
    Url: "http://www.city.fukui.lg.jp/sub2.html",
    Temp_Jan: "2.5",
    Temp_July: "27.0",
    Snow_Jan: "147cm",
    Bicthe_num: "181",
    Bicthe_rate: "0.069%",
    Carthe_num: "3",
    Carthe_rate: "0.001%",
    Carac_num: "380",
    Carac_rate: "0.145%",
    Snathe_num: "1",
    Snathe_rate: "0.0004%",
  },
  {
    id: "302",
    Pre: "福井県",
    Mun: "敦賀市",
    Pop: "64186",
    Url: "https://www.city.tsuruga.lg.jp/",
    Temp_Jan: "4.7",
    Temp_July: "27.3",
    Snow_Jan: "61cm",
    Bicthe_num: "23",
    Bicthe_rate: "0.03%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "85",
    Carac_rate: "0.13%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "303",
    Pre: "福井県",
    Mun: "小浜市",
    Pop: "28941",
    Url: "http://www1.city.obama.fukui.jp/",
    Temp_Jan: "4.1",
    Temp_July: "26.9",
    Snow_Jan: "7cm",
    Bicthe_num: "5",
    Bicthe_rate: "0.02%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "16",
    Carac_rate: "0.06%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "304",
    Pre: "福井県",
    Mun: "大野市",
    Pop: "31221",
    Url: "http://www.city.ono.fukui.jp/",
    Temp_Jan: "0.4",
    Temp_July: "25.6",
    Snow_Jan: "288cm",
    Bicthe_num: "4",
    Bicthe_rate: "0.01%",
    Carthe_num: "1",
    Carthe_rate: "0.003%",
    Carac_num: "19",
    Carac_rate: "0.06%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "305",
    Pre: "福井県",
    Mun: "勝山市",
    Pop: "22097",
    Url: "https://www.city.katsuyama.fukui.jp/",
    Temp_Jan: "1.0",
    Temp_July: "25.3",
    Snow_Jan: "NULL",
    Bicthe_num: "0",
    Bicthe_rate: "0%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "16",
    Carac_rate: "0.07%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "306",
    Pre: "福井県",
    Mun: "鯖江市",
    Pop: "68323",
    Url: "https://www.city.sabae.fukui.jp/",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "31",
    Bicthe_rate: "0.05%",
    Carthe_num: "1",
    Carthe_rate: "0.001%",
    Carac_num: "97",
    Carac_rate: "0.14%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "307",
    Pre: "福井県",
    Mun: "あわら市",
    Pop: "27410",
    Url: "http://www.city.awara.lg.jp/",
    Temp_Jan: "3.4",
    Temp_July: "26.0",
    Snow_Jan: "NULL",
    Bicthe_num: "6",
    Bicthe_rate: "0.02%",
    Carthe_num: "2",
    Carthe_rate: "0.007%",
    Carac_num: "28",
    Carac_rate: "0.10%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "308",
    Pre: "福井県",
    Mun: "越前市",
    Pop: "80496",
    Url: "https://www.city.echizen.lg.jp/index3.html",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "136cm",
    Bicthe_num: "24",
    Bicthe_rate: "0.03%",
    Carthe_num: "2",
    Carthe_rate: "0.002%",
    Carac_num: "52",
    Carac_rate: "0.07%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "309",
    Pre: "福井県",
    Mun: "坂井市",
    Pop: "88369",
    Url: "https://www.city.fukui-sakai.lg.jp/",
    Temp_Jan: "2.3",
    Temp_July: "26.4",
    Snow_Jan: "NULL",
    Bicthe_num: "25",
    Bicthe_rate: "0.03%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "98",
    Carac_rate: "0.11%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "310",
    Pre: "福井県",
    Mun: "永平寺町",
    Pop: "18961",
    Url: "http://www.town.eiheiji.lg.jp/",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "2",
    Bicthe_rate: "0.01%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "11",
    Carac_rate: "0.06%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "311",
    Pre: "福井県",
    Mun: "池田町",
    Pop: "2403",
    Url: "http://www.town.ikeda.fukui.jp/",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "0",
    Bicthe_rate: "0%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "0",
    Carac_rate: "0%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "312",
    Pre: "福井県",
    Mun: "南越前町",
    Pop: "9957",
    Url: "http://www.town.minamiechizen.lg.jp/",
    Temp_Jan: "1.3",
    Temp_July: "25.1",
    Snow_Jan: "176cm",
    Bicthe_num: "1",
    Bicthe_rate: "0.001%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "3",
    Carac_rate: "0.03%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "313",
    Pre: "福井県",
    Mun: "越前町",
    Pop: "20079",
    Url: "http://www.town.echizen.fukui.jp/index.html",
    Temp_Jan: "5.5",
    Temp_July: "26.5",
    Snow_Jan: "NULL",
    Bicthe_num: "2",
    Bicthe_rate: "0.01%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "14",
    Carac_rate: "0.07%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "314",
    Pre: "福井県",
    Mun: "美浜町",
    Pop: "9151",
    Url: "https://www.town.fukui-mihama.lg.jp/",
    Temp_Jan: "4.4",
    Temp_July: "26.6",
    Snow_Jan: "NULL",
    Bicthe_num: "1",
    Bicthe_rate: "0.01%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "15",
    Carac_rate: "0.2%",
    Snathe_num: "1",
    Snathe_rate: "0.01%",
  },
  {
    id: "315",
    Pre: "福井県",
    Mun: "高浜町",
    Pop: "10310",
    Url: "http://www.town.takahama.fukui.jp/",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "0",
    Bicthe_rate: "0%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "7",
    Carac_rate: "0.07%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "316",
    Pre: "福井県",
    Mun: "おおい町",
    Pop: "7895",
    Url: "http://www.town.ohi.fukui.jp/index.html",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "0",
    Bicthe_rate: "0%",
    Carthe_num: "1",
    Carthe_rate: "0.01%",
    Carac_num: "7",
    Carac_rate: "0.09%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
  {
    id: "317",
    Pre: "福井県",
    Mun: "若狭町",
    Pop: "13966",
    Url: "http://www.town.fukui-wakasa.lg.jp/",
    Temp_Jan: "NULL",
    Temp_July: "NULL",
    Snow_Jan: "NULL",
    Bicthe_num: "1",
    Bicthe_rate: "0.007%",
    Carthe_num: "0",
    Carthe_rate: "0%",
    Carac_num: "9",
    Carac_rate: "0.06%",
    Snathe_num: "0",
    Snathe_rate: "0%",
  },
];
